---
# handlers file for sonarqube

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted
    daemon_reload: yes
  become: true

- name: Restart SonarQube
  systemd:
    name: sonarqube
    state: restarted
    daemon_reload: yes
  become: true
