# roles/jenkins/tasks/main.yml
---
- name: Ensure Java is installed
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present

- name: Add Jenkins repository keyring
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: "0644"

- name: Add Jenkins repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins
    mode: "0644"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Ensure Jenkins is started and enabled
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to start up
  wait_for:
    port: 8080
    delay: 30
    timeout: 300

- name: Get initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_initial_password
  changed_when: false

- name: Print Jenkins initial admin password
  debug:
    var: jenkins_initial_password.stdout
